import os
import glob
import shutil
import subprocess

# Change these variables as needed for your folder paths.
root = os.path.abspath(os.path.dirname(__file__))
jupyter_folder = os.path.join(root, '_posts')
posts_folder = os.path.join(root, '_posts')
assets_folder = os.path.join(root, 'assets', 'jupyter')

debug = False

r = len(root)
s = len(jupyter_folder)

jupyter_files = []

for dir, _, _ in os.walk(jupyter_folder):
    if '.ipynb_checkpoints' not in dir:
        jupyter_files.extend(glob.glob(os.path.join(dir, '*.ipynb')))

for j in jupyter_files:
    subprocess.check_output('jupyter nbconvert {} --to markdown'.format(j),
                            shell=True)
    f = os.path.splitext(j)[0]      # Jupyter file without extension
    jr = os.path.dirname(f)[s:]     # Folder directories relative to Jupyter folder
    md1 = f + '.md'                 # Markdown file generated by nbconvert

    # Markdown file to write to posts
    if jr in ['/', '\\', '']:
        md2 = posts_folder + '/' + os.path.split(md1)[1]
    else:
        md2 = posts_folder + os.path.join(jr, os.path.split(md1)[1])

    a1 = f + '_files'               # Assets folder generated by nbconvert
    a2 = assets_folder + a1[s:]     # Folder to move assets to.

    # Markdown path for asset locations
    if os.path.split(a2)[0][r:] not in ['/', '\\', '']:
        a = '{{ site.url }}%s/' % os.path.split(a2)[0][r:].replace('\\', '/')
    else:
        a = '{{ site.url }}/'

    if debug:
        print('Jupyter file:', j)
        print('Jupyter file without extension:', f)
        print('Original MD:', md1)
        print('New MD:', md2)
        print('Existing Assets:', a1)
        print('New Assets:', a2)
        print('Assets Relative Path:', a)

    # Open generated markdown file, read, and replace asset location strings
    with open(md1, 'rt') as file:
        reader = file.read()
        data = reader.replace('![png](', '![png](%s' % a)

    # Remove generated markdown file
    os.remove(md1)

    # Create folder in posts folder if it doesn't already exist.
    try:
        os.makedirs(os.path.dirname(md2))
    except:
        print('Directory already exists and will not be created :: %s' % md2)

    # Write new markdown file to posts folder
    with open(md2, 'wt') as file:
        file.truncate()
        file.write(data)

    # Remove existing assets
    try:
        shutil.rmtree(a2)
    except:
        print('Directory does not exist or cannot be deleted :: %s' % a2)

    # Create assets folder if it doesn't already exist.
    try:
        os.makedirs(os.path.split(a2)[0])
    except:
        print('Directory already exists and will not be created :: %s' % os.path.split(a2)[0])

    # Move nbconvert generated assets folder to new location
    try:
        shutil.move(a1, a2)
    except:
        print('Could not move folder :: %s to %s' %(a1, a2))
