#!/usr/bin/env python

import os
import sys
from jup2jek import Jup2Jek
from jup2jek.scripts import Jup2JekArgParser

if __name__ == '__main__':
    root = os.getcwd()

    p = Jup2JekArgParser()
    a = p.parse_args(sys.argv[1:])

    j = Jup2Jek(root, a.options)
    j.convert_notebooks()
